'use client';

import React, { useState } from 'react';
import {
  TrendingUp, Eye, Sparkles, Award, Zap, Clock, ThumbsUp,
  Target, BarChart3, ArrowUpRight, CheckCircle2, AlertCircle
} from 'lucide-react';
import { AppLayout } from '../../components/layout/app-layout';
import { Card, CardTitle, CardDescription } from '../../components/ui/card';
import { Button } from '../../components/ui/button';
import { Badge } from '../../components/ui/badge';

export default function CreatorIntelligencePage() {
  const [topic, setTopic] = useState('Spider-Man AI Trailer Breakdown');

  const intelligenceData = {
    viralityScore: 94,
    hookRetention: '92.4%',
    completionRate: '78.1%',
    ctrEstimate: '9.2%',
    recommendedTimes: ['5:00 PM IST (Peak YouTube)', '8:30 PM IST (Peak Instagram)', '12:15 PM IST (Peak TikTok)'],
    trendingKeywords: ['AI Trailer', 'Spider-Man 2026', 'Veo 4K', 'Kinetic SFX', 'Unreal Engine 5'],
    actionableAdvice: [
      'Hook Score: Excellent (First 3 seconds have high visual motion)',
      'Thumbnail CTR Boost: Increase subtitle font contrast by +15%',
      'Retention Warning: Add sound effect cue at 00:14 mark to prevent viewer drop-off',
    ],
  };

  return (
    <AppLayout title="Creator Intelligence & Virality Engine" subtitle="AI-driven retention curves, CTR optimization, and posting schedule insights">
      <div className="space-y-6 max-w-6xl">
        {/* Top Intelligence Metrics */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
          <Card glass className="p-4 space-y-2">
            <div className="flex items-center justify-between text-xs text-white/50">
              <span>Predicted Virality Score</span>
              <Award className="h-4 w-4 text-amber-400" />
            </div>
            <p className="text-3xl font-bold text-amber-300 font-mono">{intelligenceData.viralityScore}/100</p>
            <span className="text-[10px] text-amber-400/80 font-medium">Top 5% Potential Viral Reach</span>
          </Card>

          <Card glass className="p-4 space-y-2">
            <div className="flex items-center justify-between text-xs text-white/50">
              <span>3-Second Hook Retention</span>
              <Zap className="h-4 w-4 text-emerald-400" />
            </div>
            <p className="text-3xl font-bold text-emerald-400 font-mono">{intelligenceData.hookRetention}</p>
            <span className="text-[10px] text-emerald-300 font-medium">Above YouTube Shorts Benchmark</span>
          </Card>

          <Card glass className="p-4 space-y-2">
            <div className="flex items-center justify-between text-xs text-white/50">
              <span>Estimated Mobile CTR</span>
              <Eye className="h-4 w-4 text-purple-400" />
            </div>
            <p className="text-3xl font-bold text-purple-300 font-mono">{intelligenceData.ctrEstimate}</p>
            <span className="text-[10px] text-purple-300 font-medium">+2.4% vs Niche Average</span>
          </Card>

          <Card glass className="p-4 space-y-2">
            <div className="flex items-center justify-between text-xs text-white/50">
              <span>Total Video Completion</span>
              <TrendingUp className="h-4 w-4 text-cyan-400" />
            </div>
            <p className="text-3xl font-bold text-cyan-300 font-mono">{intelligenceData.completionRate}</p>
            <span className="text-[10px] text-cyan-300 font-medium">Loop ending optimized</span>
          </Card>
        </div>

        {/* Intelligence Actions & Schedule */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <Card glass className="p-6 space-y-4">
            <CardTitle className="text-base flex items-center gap-2">
              <Sparkles className="h-4 w-4 text-amber-400" /> AI Actionable Virality Boosters
            </CardTitle>
            <CardDescription>Real-time suggestions generated by 22-Agent Retention Predictor</CardDescription>

            <div className="space-y-3">
              {intelligenceData.actionableAdvice.map((item, idx) => (
                <div key={idx} className="p-3 rounded-xl bg-white/[0.03] border border-white/10 flex items-start gap-3">
                  <CheckCircle2 className="h-4 w-4 text-emerald-400 shrink-0 mt-0.5" />
                  <span className="text-xs text-white/80">{item}</span>
                </div>
              ))}
            </div>
          </Card>

          <Card glass className="p-6 space-y-4">
            <CardTitle className="text-base flex items-center gap-2">
              <Clock className="h-4 w-4 text-purple-400" /> Optimal Cross-Platform Posting Schedule
            </CardTitle>
            <CardDescription>Maximized audience online times across platforms</CardDescription>

            <div className="space-y-3">
              {intelligenceData.recommendedTimes.map((time, idx) => (
                <div key={idx} className="p-3 rounded-xl bg-purple-500/10 border border-purple-500/20 flex items-center justify-between">
                  <span className="text-xs font-semibold text-purple-200">{time}</span>
                  <Badge variant="completed">Optimal</Badge>
                </div>
              ))}
            </div>
          </Card>
        </div>
      </div>
    </AppLayout>
  );
}
